services:
  - type: web_service
    name: proyecto-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        value: <your-db-host>
      - key: DB_USER
        value: <your-db-user>
      - key: DB_PASS
        value: <your-db-pass>
      - key: DB_NAME
        value: proyecto_db
